accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path("signup/", views.signup, name="signup"),
        
    path('login/', views.CustomLoginView.as_view(), name='login'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]

devapp/urls.py
from django.urls import path
from . import views
from devapp.views import IndexTemplateView
from .views import detectBoardgame

app_name = 'devapp'
urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('detectBdg', views.detectBoardgame.as_view(), name='detectBdg'),
]

devproject/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include
from . import settings_common
from django.http import HttpResponse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('devapp.urls')),
    path("accounts/", include("accounts.urls")),
     # LB からのヘルスチェックに答えるためのURLで、アプリが起動していれば常に 200 OK を返す
    path('status/', lambda request: HttpResponse()),
]

# 以下、DEBUG=Trueの時用
urlpatterns += static(settings_common.STATIC_URL, document_root=settings_common.STATIC_ROOT)
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_common.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("メールアドレスは必ず書いてね")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

devapp/models.py
from django.db import models

class chatgpt_answer_log(models.Model):
    answer_1 = models.CharField(max_length=254)
    answer_2 = models.CharField(max_length=254)
    answer_3 = models.CharField(max_length=254)
    answer_4 = models.CharField(max_length=254)
    answer_5 = models.CharField(max_length=254)
    answer_6 = models.CharField(max_length=254)
    answer_7 = models.CharField(max_length=254)
    answer_8 = models.CharField(max_length=254)
    answer_9 = models.CharField(max_length=254)
    answer_10 = models.CharField(max_length=254)
    answer_11 = models.CharField(max_length=254)
    answer_12 = models.CharField(max_length=254)
    answer_13 = models.CharField(max_length=254)
    answer_14 = models.CharField(max_length=254)
    answer_15 = models.CharField(max_length=254)
    create_user = models.CharField(max_length=254)
    create_date = models.DateTimeField()

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.shortcuts import render, redirect
from .models import CustomUser

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView

class EmailUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("email",)

def signup(request):
    if request.method == "POST":
        form = EmailUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("devapp:index")
    else:
        form = EmailUserCreationForm()
    return render(request, "signup.html", {"form": form})
    

class CustomLoginView(LoginView):
    template_name = 'login.html'


# def signup(request):
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             login(request, user)
#             return redirect('devapp:index')
#     else:
#         form = UserCreationForm()
#     return render(request, 'signup.html', {'form': form})
    

devapp/templates/base.html
{% load static %}

<html lang="ja">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="ボードゲーム名で検索するとどんなゲームなのかChatGPTが答えてくれます。また、ボードゲームの写真から検索してもらうことも可能です。">
      <meta name="author" content="">
      <link href="{% static 'favicon/favicon.ico' %}" rel="icon">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <title>{% block title %}ボードゲームアカデミー{% endblock %}</title>
      <link rel="stylesheet" href="{% static 'css/custom.css' %}">
      <link href='https://fonts.googleapis.com/css?family=Actor' rel='stylesheet' type='text/css'>
      <link rel="stylesheet" href="{% static 'css/loading.css' %}"/>
      {% block css %}
      {% endblock %}
      <script src="{% static 'js/three.min.js' %}"></script>
      {% if GOOGLE_ANALYTICS_TRACKING_ID %}
        {% include 'ga.html' %}          
      {% endif %}
    </head>
    <body class="lazyload">
      <header id="header">
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
              <div class="container">
                {% comment %}
                <!--<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
                <!--  <span class="navbar-toggler-icon"></span>-->
                <!--</button>-->
                <!--<div class="collapse navbar-collapse" id="navbarSupportedContent">-->
                <!--  <ul class="navbar-nav me-auto mb-2 mb-lg-0">-->
                <!--    <li class="nav-item">-->
                <!--      <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>-->
                <!--    </li>-->
                <!--    <li class="nav-item">-->
                <!--      <a class="nav-link" href="{% url 'accounts:signup' %}">Sign up</a>-->
                <!--    </li>-->
                <!--  </ul>-->
                <!--</div>-->
                {% endcomment%}
              </div>
          </nav>
      </header>
      
      {% comment %}
      <!--<div class="header">-->
      <!--  <button id="menuButton" class="menuButton">-->
      <!--    <div class="menuLine"></div>-->
      <!--    <div class="menuLine"></div>-->
      <!--    <div class="menuLine"></div>-->
      <!--  </button>-->
      <!--</div>-->
      <!--<div id="sideMenu" class="sideMenu">-->
      <!--  <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>-->
      <!--  <a class="nav-link" href="{% url 'accounts:signup' %}">Sign up</a>-->
      <!--</div>-->
      {% endcomment%}
      
      {% if messages %}
      <div class="container">
          <div class="row">
              <ul class="messages" style="list-style: none;">
                  {% for message in messages %}
                  <li {%if message.tags %} class="{{message.tags}}" {% endif %}>
                      {{ message | linebreaksbr }}
                  </li>
                  {% endfor %}
              </ul>
          </div>
      </div>
      {% endif %}
      
      {% include 'loading.html' %}   
      
      <!--3D背景画面用-->
      {% block extrabody %}{% endblock %}
      
      <!--ここに各画面ごとのデザインを設定-->
      {% block content %}
      {% endblock %}
      <script src="{% static 'js/base.js' %}"></script>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
      <script src="https://kit.fontawesome.com/9d69cfe720.js" crossorigin="anonymous"></script>

      {% block javascript %}
      {% endblock %}
  
    </body>
</html>

devapp/templates/detecrBdg.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
  <link href="{% static 'css/detectBdg.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<style type="text/css">
.result-card {
  background-image: url("{% static 'images/background-ue.png' %}");
}
</style>

<div class="container">

  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
        
      <div class="image-container">
        <a href="{% url 'devapp:index' %}">
          <img class="lazyload" src="{% static 'images/mainImg.png' %}" >
        </a>
      </div>
      
      {% if image_url %}
      <div class=" align-center">
        <img src="{{ MEDIA_URL }}{{ image_url }}" alt="Image" class="rounded img-fluid display-image">
      </div>    
      {% endif %}
      
      {% if gptResultList.0 == 'gpterror' %}
          <div class="result-card">
              <p>ChatGPTのサーバが込み合っているためエラーとなりました。少し時間をあけてから再度お試しください。</p>
          </div>
      {% elif gptResultList %}
          <div class="result-card">
              <h2 class="result-title align-center">ChatGPTの答え</h2>
              <div class="result-detail">
                <p class="result-question">1.ボードゲーム名</p>
                <p class="result-answer">{{ gptResultList.0 }}</p>
                <p class="result-question">2.どんなゲーム？</p>
                <p class="result-answer">{{ gptResultList.1 }}</p>
                <p class="result-question">3.似ているボードゲームは？</p>
                <a href="https://www.google.com/search?q={{ gptResultList.2 }} ボードゲーム" target="_blank" class="resultUrl"><p class="result-answer">{{ gptResultList.2 }}</p></a>
                <a href="https://www.google.com/search?q={{ gptResultList.3 }} ボードゲーム" target="_blank" class="resultUrl"><p class="result-answer">{{ gptResultList.3 }}</p></a>
                <a href="https://www.google.com/search?q={{ gptResultList.4 }} ボードゲーム" target="_blank" class="resultUrl"><p class="result-answer">{{ gptResultList.4 }}</p></a>
                <p class="text-chatgpt">powered by ChatGPT</p>
                <a class="back-btn" href="{% url 'devapp:detectBdg' %}">
                  <i class="fa-solid fa-caret-left"></i> 戻る
                </a>
              </div>
          </div>
          <div class="warningInfoArea">
            <p>ChatGPTのサーバが混み合っている場合は<br />
            エラーになったり、回答が遅くなる場合があります</p>
          </div>
      {% else %}
      <div id="textArea" class="align-center">
        <p class="area-title">ボードゲームの名前を入力↓</p>
        <div class="search-box">
          <input type="text" name="inputText" id="inputText" class="search-input" placeholder="(例)カタン">
          <button type="submit" name="searchBdgByText" id="searchBdgByText" class="search-button"><i class="fas fa-search"></i></button>
        </div>
      </div>
      <div id="imageArea" class="align-center">
        <p class="area-title">ボードゲームを撮影↓</p>
        <div id="cameraBtnPosision">
          <!--ここにカメラを起動するボタンが動的にセットされる-->
        </div>
        <input type="submit" name="searchBdg" id="searchBdg" value="カメラ起動" hidden="hidden">
        <p class="camera-area-warning-text">※画像からボードゲームの名前が読み取れない場合失敗します</p>
      </div>
      <div class="d-flex justify-content-center btnSwitchArea">
        <div class="btn-group btn-group-toggle mx-auto switchIconArea" data-toggle="buttons">
          <label class="btn btn-secondary active lblBtnSwitchLeft">
            <input type="radio" name="formChoice" id="textIcon" autocomplete="off">
            <i class="fa-solid fa-pen icon-size"></i>
          </label>
          <label class="btn btn-secondary lblBtnSwitchRight" id="lblImageIcon">
            <input type="radio" name="formChoice" id="imageIcon" autocomplete="off">
            <i class="fa-solid fa-camera icon-size"></i>
          </label>
        </div>
      </div>
      <div class="outer-catchArea">
        <div class="catchArea">
          <div class="catch-copy-area align-center">
            <p class="catchTextGroup1">「名前は聞いたことある」「見たことはある」</p>
            <p class="catchTextGroup2">『でも、どういうゲーム？！』</p>
            <p class="catchTextGroup2 catchText3">そんな疑問にChatGPTが</p>
            <p class="catchTextGroup2">答えてくれます！</p>
          </div>
          <div class="warningInfoArea">
            <p>ChatGPTのサーバが混み合っている場合は<br />
            エラーになったり、回答が遅くなる場合があります</p>
          </div>
        </div>
      </div>
      {% endif %}
  </form>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/detectBdg.js' %}"></script>
<script>
window.onload = function() {
    var resultCardExists = document.getElementsByClassName('result-card').length > 0;
    var bodyElement = document.getElementsByTagName('body')[0];
    var imageElement = document.querySelector('.image-container img.lazyload');
    
    // 検索画面と結果画面で背景画像を切替
    if (resultCardExists) {
        bodyElement.style.backgroundImage = 'url("{% static bg_result %}")';
        imageElement.classList.add('result-view');
    } else {
        bodyElement.style.backgroundImage = 'url("{% static bg_search %}")';
        imageElement.classList.add('search-view');
    }
    
    // CSS適用後画面表示
    if(imageElement.complete) {
        imageElement.classList.add('loaded');
    } else {
        imageElement.addEventListener('load', function() {
            this.classList.add('loaded');
        });
    }
}
</script>
{% endblock %}

devapp/templates/ga.html
<script async src="https://www.googletagmanager.com/gtag/js?id={{ GOOGLE_ANALYTICS_TRACKING_ID }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{ GOOGLE_ANALYTICS_TRACKING_ID }}');
</script>

devapp/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
  <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block extrabody %}
<div id="background">
  <div id="overlay"></div>
</div>
<script>
    var skyboxImageURL = "{% static 'images/index-bgImg.jpg' %}"; //skybox.jsの読み込みより前に記載
</script>
<script src="{% static 'js/skybox.js' %}"></script>
<style type="text/css">
  /*<!--3D画像用の設定-->*/
  canvas { display: block; }
  #background {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      z-index: 0;
      background-color: #333333;
  }
  #overlay {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: rgba(0, 0, 0, 0.3);
      /*background: rgba(255, 255, 255, 0.5);*/
      z-index: 1;
  }
  canvas {
      position: absolute;
      top: 0;
      left: 0;
  }
</style>
{% endblock %}

{% block content %}
  <div class="container main">
    <div style="position: relative; z-index: 1;">
      <h1 class="title-text">ボードゲームアカデミー</h1>
      <br />
      <a class="start-button" title="画像" href="{% url 'devapp:detectBdg' %}"><span>Get Started</span></a>
    </div>
  </div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}

devapp/templates/loading.html
{% load static %}
<div id="loading" style="display: none;">
  <div class="loader">
    <div class="container text-center">
      <div class="col-sm-2">
        <div class="sp sp-clock"></div>
      </div>
    </div>
  </div>
</div>